### ISSUE TITLE
Cypress tests for custom 404 page

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#516]
### What feature would you like to have?

Once we merge the PR that adds a custom 404 page (#514), I'd like to add some Cypress tests.

### What problem will this feature solve?

Confidence that we're not inadvertently breaking the 404 page functionality in some way with later updates/refactorings.

### Do you want to help make the feature?

Yes

**Comment by Belco90** [comment]
I actually prefer to address this in the original ticket itself: from now on features and tests should go together.

**Comment by HonkingGoose** [comment]
> I actually prefer to address this in the original ticket itself: from now on features and tests should go together.

I didn't know if you wanted to "hold up" a feature PR because there are no tests.

So the rule is: "Features and tests belong together", and I think also: "No new feature unless we have accompanying tests"?

**Comment by Belco90** [comment]
> So the rule is: "Features and tests belong together", and I think also: "No new feature unless we have accompanying tests"?

That's the spirit! Unless there is a really powerful reason to skip it, we need to work that way from now on so 1) we don't introduce new stuff without tests and 2) we focus on testing existing stuff before updating/refactoring existing features (in terms of how the comparator works, it's fine to update the UI with the tests we have for now). Otherwise, we would keep adding new stuff and never catch up on having tests for covering the basic use cases.

**Comment by HonkingGoose** [comment]
Agree, it's a good idea to always have tests, and to strive for full coverage if possible.
I find that having a good test suite makes you less anxious to change things, as you know the automated tests have your back. 😄
